language: go

go:
  - "1.11.x"

services:
  - mysql
  - redis-server
  
before_script:
  - make clean-all
  - make dep-install
  - make deps
  - make golint-install
  - make lint
  - make create-dotenv
  - mysql -uroot -e "create database test"

script: 
  - make
  - make test
