language: go

go:
  - "1.11.x"

sudo: required

services:
  - mysql
  - redis-server
  - docker

before_script:
  - make clean-all
  - make dep-install
  - make deps
  - make golint-install
  - make lint
  - mysql -uroot -e "create database test"

env:
  global:
    DB_USER=root
    DB_URL=localhost:3306
    REDIS_URL=localhost:6379

script:
  - make
  - make test

after_success:
  - make docker-build

deploy:
  - provider: script
    script: make docker-push
    on:
      # branch: master
      branch:
        - hhiroshell/travis-github
        - release
      condition: $TRAVIS == "true"
  - provider: script
    script: make github-pr
    on:
      # branch: master
      branch:
        - hhiroshell/travis-github
        - release
        - master
      condition: $TRAVIS == "true"

# after_deploy:
#   - make github-pr