language: go

go:
  - "1.11.x"

sudo: required

services:
  - mysql
  - redis-server
  - docker

before_script:
  - make create-dotenv-for-travis
  - make clean-all
  - make dep-install
  - make deps
  - make golint-install
  - make lint
  - mysql -uroot -e "create database test"

env:
  global:
    DB_USER=root
    DB_URL=localhost:3306
    REDIS_URL=localhost:6379

script:
  - make
  - make test

after_success:
  - make docker-build

deploy:
  skip_cleanup: true
  - provider: script
    script: make docker-push
    on:
      condition: $TRAVIS == "true"
      branch:
        - release
  - provider: script
    script: make update-kustomize-action
    on:
      condition: $TRAVIS == "true"
      branch:
        - release
        - master
