language: go

go:
  - "1.11.x"

sudo: required

services:
  - mysql
  - redis-server
  - docker

before_script:
  - make clean-all
  - make dep-install
  - make deps
  - make golint-install
  - make lint
  - mysql -uroot -e "create database test"
  
env:
  global:
    DB_USER=root
    DB_URL=localhost:3306
    REDIS_URL=localhost:6379

script: 
  - make
  - make test

after_success:
  - find .
  - make docker-build

deploy:
  provider: script
  script: find . && make docker-push
  on:
    branch: hhiroshell/docker-on-travis
    condition: $TRAVIS == "true"